LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := Signal

LOCAL_CERTIFICATE := platform

# Use SIGNAL_APK_PATH if set. Need to export SIGNAL_APK_PATH
ifdef SIGNAL_APK_PATH
LOCAL_SRC_FILES := $(SIGNAL_APK_PATH)
else
LOCAL_SRC_FILES := signal.apk
endif

LOCAL_MODULE_CLASS := APPS
LOCAL_OVERRIDES_PACKAGES := messaging
LOCAL_PRIVILEGED_MODULE := true

LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)
